version: 2
python:
  install:
  - path: .
    extra_requirements:
      - docs

# required boilerplate readthedocs/readthedocs.org#10401
build:
  os: ubuntu-22.04
  tools:
    python: "3"
  jobs:
    post_checkout:
    - 'git fetch --unshallow --tags || true'
    pre_install:
    - git update-index --assume-unchanged docs/conf.py
