name: Pre-merge tests

on:
  pull_request:
    branches:
    - main

permissions:
  contents: read

jobs:
  changelog:
    name: Check for a changelog fragment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        # Required to check commit history in changed-files step below
        fetch-depth: 0
    - name: Get changed files
      id: changed-files
      uses: step-security/changed-files@v46
      with:
        files: changelog.d/*.*
    - name: Fail if no changelog fragment is present
      env:
        CHANGES_ADDED_FILES_COUNT: ${{steps.changed-files.outputs.added_files_count}}
        CHANGES_DELETED_FILES_COUNT: ${{steps.changed-files.outputs.deleted_files_count}}
        CHANGES_OTHER_MODIFIED_FILES: ${{steps.changed-files.outputs.other_modified_files}}
      run: |
        if [[ "$CHANGES_DELETED_FILES_COUNT" -eq 0 ]]; then
          # Normal PR: a changelog fragment should be added
          if [[ "$CHANGES_ADDED_FILES_COUNT" -gt 0 ]]; then
            echo "::debug:: Found that a changelog file was added"
            exit 0
          # Exception: if the only file being updated is .pre-commit-config.yaml
          # and at least one commit in the PR is generated by the pre-commit bot.
          # This is a heuristic to detect automatic pre-commit update PRs.
          elif [[ "$CHANGES_OTHER_MODIFIED_FILES" == ".pre-commit-config.yaml" ]]; then
            if ! git fetch origin "$GITHUB_BASE_REF:refs/pr-base" "$GITHUB_HEAD_REF:refs/pr-head"; then
              echo "::error:: Fetch failed (infrastructure error)"
              exit 1
            elif [[
              -n "$(
                git rev-list --author='\+pre-commit-ci\[bot\]@users.noreply.github.com' "refs/pr-base..refs/pr-head"
              )"
            ]]; then
              echo "::debug:: Found that this PR looks like an automatic pre-commit hook update"
              exit 0
            fi
          fi
          echo "::error:: Please add a changelog fragment using towncrier"
          exit 1
        else
          # Changelog update PR: CHANGELOG.rst should be modified and changelog.d/!(.gitkeep) should be deleted
          if [[ "$CHANGES_ADDED_FILES_COUNT" -gt 0 ]]; then
            echo "::error:: Changelog fragments were both added and deleted"
            exit 1
          else
            echo "::debug:: No changelog fragments were added"
          fi
          if [[ " $CHANGES_OTHER_MODIFIED_FILES " != *\ CHANGELOG.rst\ * ]]; then
            echo "::error:: Changelog fragments were deleted but CHANGELOG.rst was not modified"
            exit 1
          else
            echo "::debug:: Found that CHANGELOG.rst was modified"
          fi
          if [[ "$(git ls-files 'changelog.d/*.*')" != "changelog.d/.gitkeep" ]]; then
            echo "::error:: Some but not all changelog fragments were deleted"
            exit 1
          else
            echo "::debug:: Found that all changelog fragments were deleted"
          fi
        fi
